[package]
name = "progset2"
version = "0.1.0"
edition = "2021"


[dependencies]
csv = "1.3.0"
rand = "0.8.5"
thiserror = "1.0.57"
serde = { version = "1.0.197", features = ["derive"] }
serde_json = "1.0.114"
