[package]
name = "progset1"
version = "0.1.0"
edition = "2021"


[dependencies]
thiserror = "1.0.56"
rand = "0.8.5"
csv = "1.3.0"
serde = { version = "1.0.196", features = ["derive"] }
serde_json = "1.0.113"
