/// Generates minimum spanning trees using Prim's algorithm. Works
/// on all graphs that can be generated by the graph_gen module.
pub mod mst;

/// Contains a binary-heap that's been specially adapted for use
/// with Prim's or Dijkstra's algorithm.
mod prim_heap;
pub use prim_heap::Weight;

/// Generates complete graphs of various dimensions
/// based on the problem set specification.
/// - One dimensional graphs have fixed IDs and random weights.
/// - [2, 3, 4] dimensional graphs have random coordinates and
/// edge weights determined by distance.
pub mod graph_gen;

/// Handlers and data types for responding to user input.
pub mod cli;

/// Contains an abstraction over floating point
/// numbers that allows them to be safely used as keys in
/// a hash map.
mod decimal;

/// Defines a crate-wide error type.
pub mod error;

/// Retrieves bulk data for tests (mostly used by prim_heap)
#[cfg(test)]
mod test_data;
